articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('/<slug>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('edit_article/<slug>', views.edit_article, name='edit_article'),
    path('delete_article/<slug>', views.delete_article, name='delete_article'),
    path('<slug>/like', views.like, name='like'),
    path('<slug>/dislike', views.dislike, name='dislike'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('edit_comment/<int:pk>', views.edit_comment, name='edit_comment'),


]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('articles.urls', 'blog'), namespace='articles')),
    path('users/', include(('users.urls', 'blog'), namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, null=True)
    thumb = models.ImageField(default='img.jpg', blank=True)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')

    def __str__(self):
        return self.title

    def snippet(self):
        return self.text[:20] + '... read more'

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()


class Comment(models.Model):
    article = models.ForeignKey(Article, default=None, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.article} - {self.body[:5]}"

users/models.py
from django.db import models

articles/forms.py
from django import forms
from . import models


class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    text = forms.CharField(widget=forms.TextInput(attrs={'class': 'textarea', 'size': '40'}))
    slug = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = models.Article
        fields = ['title', 'text', 'slug', 'thumb']


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'textarea',
        'size': '40',
        'placeholder': 'Write your comment here...'
    }))

    class Meta:
        model = models.Comment
        fields = ['body', ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Create any username'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Create any password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Write username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Write password'}))

    class Meta:
        model = User
        fields = ['username', 'password']

articles/views.py
from . import forms
from django.shortcuts import render, redirect
from .models import Article, Comment
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def home(request):
    search = request.GET.get('search')
    articles = Article.objects.all().order_by('date')
    articles = articles.filter(Q(title__icontains=search) | Q(text__icontains=search)) if search else articles
    return render(request, 'articles_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    form = forms.CommentForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.article = article
        instance.save()
        return redirect('articles:article_detail', slug=article.slug)
    return render(request, 'article_detail.html', {'article': article, 'form': form})


def article_create(request):
    form = forms.ArticleForm(request.POST or None, request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('articles:home')
    return render(request, 'article_create.html', {'form': form})


@login_required(login_url='/users/sign_in')
def edit_article(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user != article.author:
        return render(request, 'error.html', {'article': article})
    form = forms.ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=request.POST.get('slug'))
    return render(request, 'edit_article.html', {"form": form, 'article': article})


def delete_article(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:home')
    return render(request, 'delete_article.html', {'article': article})


def like(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user not in article.likes.all():
        article.likes.add(request.user)
        article.dislikes.remove(request.user)
    elif request.user in article.likes.all():
        article.likes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)


def dislike(request, slug):
    article = Article.objects.get(slug=slug)

    if request.user not in article.dislikes.all():
        article.dislikes.add(request.user)
        article.likes.remove(request.user)
    elif request.user in article.dislikes.all():
        article.dislikes.remove(request.user)
    return redirect('articles:article_detail', slug=slug)


def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.user != comment.user:
        return render(request, 'error.html', {'comment': comment})

    if request.method == 'POST':
        comment.delete()
        return redirect('articles:article_detail', slug=comment.article.slug)
    return render(request, 'delete_comment.html', {'article': comment.article})


def edit_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    form = forms.CommentForm(request.POST or None, instance=comment)

    if request.user != comment.user:
        return render(request, 'error.html', {'comment': comment})

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('articles:article_detail', slug=comment.article.slug)
    return render(request, 'edit_comment.html', {'form': form, 'article': comment.article})

users/views.py
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render
from . import forms


def sign_up(request):
    form = forms.SignUpForm(request.POST)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('users:sign_in')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    form = forms.SignInForm(data=request.POST)
    if form.is_valid() and request.method == 'POST':
        user = form.get_user()
        login(request, user)
        return redirect('articles:home')
    form = forms.SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

articles/templates/article_create.html
{% extends "base_layout.html" %}

{% block content %}
<form class="site-form has-background-light" method="post" action="{% url 'articles:article_create' %}" enctype="multipart/form-data">
   {% csrf_token %}
   {{form}}
   <div class="has-text-centered my-2">
       <button type="submit" class="button is-success">Отправить</button>
       <a href="{% url 'articles:home' %}" class="button is-danger">Отмена</a>
   </div>
</form>
{% endblock %}

articles/templates/article_detail.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
<div class="box" style=”min-width:100%”>
    {% if user == article.author %}
    <div class="has-text-right">
        <a href="{% url 'articles:edit_article' article.slug %}" class="button is-info ">
            <ion-icon name="create-outline"></ion-icon>
        </a>
        <a href="{% url 'articles:delete_article' article.slug %}" class="button is-danger">
            <ion-icon name="trash-outline"></ion-icon>
        </a>
    </div>
    {% else %}
    <div class="has-text-right">
        <p class="content has-text-grey-light">
            You can't not edit or delete this post
        </p>
    </div>
    {% endif %}
    <div class="title has-text-dark has-text-centered">{{ article }}</div>
    <img src="{{ article.thumb.url }}" alt="" class="image is-centered" style="min-width: 100%; border-radius: 5px">
    <div class="subtitle has-text-dark has-text-centered">{{ article.text }}</div>
    <div class="columns">
        <div class="column is-1">
            <form action="{% url 'articles:like' article.slug %}" method="post"
                  class="has-text-right">
                {% csrf_token %}
                <button type="submit" name="article_id" value="{{ article.id }}"
                        class="button {% if user in article.likes.all %} is-success {% endif %} ">
                    <ion-icon name="thumbs-up-outline"></ion-icon>
                    <span class="ml-2">{{ article.total_likes }}</span>
                </button>
            </form>
        </div>
        <div class="column is-1">
            <form action="{% url 'articles:dislike' article.slug %}" method="post"
                  class="has-text-right">
                {% csrf_token %}
                <button type="submit" name="article_id" value="{{ article.id }}"
                        class="button {% if user in article.dislikes.all %} is-danger {% endif %} ">
                    <ion-icon name="thumbs-down-outline"></ion-icon>
                    <span class="ml-2">{{ article.total_dislikes }}</span>
                </button>
            </form>
        </div>
    </div>
    {% if not article.comment_set.all %}
    <div class="has-text-centered has-text-grey-light is-size-5 mx-3">
        No comments yet. Be first to leave comment...
    </div>
    {% else %}
    <p class="has-text-centered is-size-3 mb-6">Comments</p>
    {% for comment in article.comment_set.all %}
    <article class="message is-info">
        <div class="message-header">
            {% if user == comment.user %}
            <p>Added by you at {{ comment.date_added }}</p>
            {% else %}
            Added by {{ comment.user }} at {{ comment.date_added }}
            {% endif %}
            {% if user == comment.user %}

        </div>
        <div class="has-text-right is-size-5">
            <a href="{% url 'articles:delete_comment' comment.pk %}" style="text-decoration: none">
                <ion-icon name="trash-outline"></ion-icon>
            </a>
            <a href="{% url 'articles:edit_comment' comment.pk %}" class="button is-info">
                <ion-icon name="create-outline"></ion-icon>
            </a>
        </div>
        {% endif %}
        <div class="message-body">{{ comment.body }}</div>
    </article>
    {% endfor %}
    {% endif %}
    <form method="POST" enctype="multipart/form-data" class="comment">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="button is-success mt-3 is-fullwidth">Submit</button>
    </form>

    <div class="has-text-grey is-size-6 has-text-right is-italic">
        <p class="datetime">Date of publication: {{ article.date }}</p>
        {% if user == article.author %}
        <p class="content">Published by you</p>
        {% else %}
        <p class="content">Published by: {{ article.author }}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

articles/templates/articles_list.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}
    <div class="container">
        <div class="columns is-centered">
            {% for article in articles %}
                <div class="column is-3">
                    <a href="{% url 'articles:article_detail' article.slug %}">
                        <div class="card has-text-centered">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-content">
                                        <p class="title has-text-dark is-2">
                                            {{ article }}
                                        </p>
                                        <p class="subtitle has-text-grey">
                                            {% if user == article.author %}
                                                by you
                                            {% else %}
                                                by {{ article.author }}
                                            {% endif %}
                                        </p>

                                    </div>
                                </div>
                                <div class="content ">
                                    {{ article.snippet }}
                                    <br>
                                    <div>{{ article.date }}</div>
                                    <div class="columns">
                                        <div class="column is-2">
                                            <div class="columns is-gapless">
                                                <div class="column">
                                                    <ion-icon name="thumbs-up-outline" class="mt-1"></ion-icon>
                                                </div>
                                                <div class="column">
                                                    <span class="ml-2">{{ article.total_likes }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="column is-2">
                                            <div class="columns is-gapless">
                                                <div class="column">
                                                    <ion-icon name="thumbs-down-outline" class="mt-1"></ion-icon>
                                                </div>
                                                <div class="column">
                                                    <span class="ml-2">{{ article.total_dislikes }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

articles/templates/base_layout.html
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</head>
<body>
<section class="hero has-background-info is-fullheight">
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a href="{% url 'articles:home' %}">
                        <img src="{% static 'images/monday.svg' %}" width="100" alt="Logo">

                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-start">
                        {% if user.is_authenticated %}
                        <a href="{% url 'articles:article_create' %}"
                           class="navbar-item my-4 button is-info is-outlined is-inverted">
                                   <span class="mr-2">
                                       <ion-icon name="book-outline"></ion-icon>
                                   </span>
                            <span>
                                        Create article
                                   </span>
                        </a>
                        {% endif %}
                    </div>
                    <div class="navbar-end">
                        {% if user.is_authenticated %}
                        <form action="{% url 'articles:home' %}" method="get">
                                <div class="field has-addons mt-4 mr-2">
                                    <div class="control">
                                        <input class="input" type="search" placeholder="Find an article" name="search">
                                    </div>
                                    <div class="control">
                                        <button class="button is-primary" type="submit">
                                            Search
                                        </button>
                                    </div>
                                </div>
                            </form>
                        <a class="navbar-item button my-4 mx-1">

                            Welcome: {{ user }}


                        </a>

                        <a href="{% url 'users:sign_out' %}" class="navbar-item my-4 button is-warning">Sign out</a>
                        {% endif %}
                    </div>


                </div>
            </div>
        </header>
    </div>
    <div class="hero-body">
        {% block content %}
        {% endblock %}
    </div>
</section>
</body>
</html>

articles/templates/delete_article.html
{% extends 'base_layout.html' %}

{% block content %}
   <form method="post" class="site-form has-background-light" style="margin-top: 200px">
       {% csrf_token %}
       <p class="content has-text-centered is-size-4 mb-4">Are you sure to delete post "{{ article }}"?</p>
       <div class="has-text-centered">
           <button type="submit" class="button is-primary">Yes</button>
           <a href="{% url 'articles:article_detail' article.slug %}" class='button is-danger'>No</a>
       </div>
   </form>
{% endblock %}

articles/templates/delete_comment.html
{% extends 'base_layout.html' %}

{% block content %}
   <form method="post" class="site-form has-background-light">
       {% csrf_token %}
       <p class="content is-size-4 mb-4">Вы действительно хотите удалить комментарий?</p>
       <div class="has-text-centered">
           <button type="submit" class="button is-primary">Подтвердить</button>
           <a href="{% url 'articles:article_detail' article.slug %}" class='button is-danger'>Отмена</a>
       </div>
   </form>
{% endblock %}

articles/templates/edit_article.html
{% extends 'base_layout.html' %}

{% block content %}
   <form class="site-form has-background-light" method="post" enctype="multipart/form-data">
       <h2 class="title is-size-2 has-text-centered">Update Article</h2>
       {% csrf_token %}
       {{ form }}
       <div class="has-text-centered my-4">
           <button class="button is-success" type="submit">Submit</button>
           <a href="{% url 'articles:article_detail' article.slug %}" class="button is-danger ">
               Back
           </a>
       </div>
   </form>
{% endblock %}

articles/templates/edit_comment.html
{% extends "base_layout.html" %}

{% block content %}
   <form class="site-form has-background-light" method="post" enctype="multipart/form-data">
   <div class="title">Edit Comment</div>
       {% csrf_token %}
       {{ form }}
       <div class="has-text-centered my-2">
           <button type="submit" class="button is-success">Отправить</button>
           <a href="{% url 'articles:article_detail' article.slug %}" class="button is-danger">Отмена</a>
       </div>
   </form>
{% endblock %}

articles/templates/error.html
{% if article %}
   <div class="title">Вы не можете удалить или изменить данный пост, так как вы не являетесь
       автором
       этого поста
   </div>
   <a href="{% url 'articles:home' %}" class="button is-success is-fullwidth">
       Вернутся на главную
   </a>
{% else %}
   <div class="title is-4">Вы не можете удалить или изменить данный комментарий, так как вы не являетесь
       автором этого комментария
   </div>
   <a href="{% url 'articles:article_detail' comment.article.slug %}" class="button is-success is-fullwidth">
       Вернутся на страницу поста
   </a>
{% endif %}

users/templates/sign_in.html
{% extends "base_layout.html" %}

{% block content %}
    <form class="site-form has-background-light has-text-centered" method="post">
        <p class="title">Sign in</p>
        {% csrf_token %}
        {% for field in form %}
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            {{ field }}
        {% endfor %}

        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success is-fullwidth">Sign in</button>
        </div>
        <hr class="has-background-grey-lighter">
        <div class="is-size-5 has-text-grey-light">Don't have an account?</div>
        <a href="{% url 'users:sign_up' %}" class="button is-ghost">
            Move to register page
        </a>
    </form>
{% endblock %}

users/templates/sign_up.html
{% extends "base_layout.html" %}

{% block content %}
    <form class="site-form has-background-light has-text-centered" method="post">
        <p class="title">Sign up</p>
        {% csrf_token %}
        {% for field in form %}
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            {{ field }}
        {% endfor %}
        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success is-fullwidth">Sign up</button>
        </div>
        <hr class="has-background-grey-lighter">
        <div class="is-size-5 has-text-grey-light">Already have an account?</div>
        <a href="{% url 'users:sign_in' %}" class="button is-ghost">
            Move to login page
        </a>
    </form>
{% endblock %}